### DISCUSSION TITLE
Debugger warning: Please pass -Xfrozen_modules=off (Docker-Compose)

### DISCUSSION THREAD

**Discussion by LHBL2003** [microsoft/debugpy#1618] [Q&A] [answered]
I am currently trying to debug a plugin for Netbox that someone else once wrote. He uses Docker Compose, which I find very interesting. I also manage to start it in debug mode. However, it takes a very long time until this message is skipped.

Can someone tell me where I have to enter the parameters?
Everything I have found so far via Google does not say where you have to specify this or how you have to specify it.

-Xfrozen_modules=off
PYDEVD_DISABLE_FILE_VALIDATION=1

Thank you very much for your help. It took me many days before I was able to debug it at all. Now I don't want to spend hours with the start. :)

**System**
Ubuntu 22.04.4 LTS

VSCode Info:
Version: 1.90.1
Commit: 611f9bfce64f25108829dd295f54a6894e87339d
Date: 2024-06-11T21:02:43.666Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.5.0-41-generic

Extensions: 
Docker v1.29.1
Python Debugger v2024.6.0

DebugPy: 1.8.2

### Docker and debug files:

```
netbox_1    | Running migrations:
netbox_1    |   No migrations to apply.
netbox_1    | 0.01s - Debugger warning: It seems that frozen modules are being used, which may
netbox_1    | 0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
netbox_1    | 0.00s - to python to disable frozen modules.
netbox_1    | 0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
netbox_1    | debugpy 1.8.2
```

The Projekt:
https://github.com/netbox-community/netbox-qrcode

develop/ Docker File Original:
```
ARG python_ver=3.12
FROM python:${python_ver}

ARG netbox_ver=master
ENV PYTHONUNBUFFERED 1

RUN mkdir -p /opt

RUN pip install --upgrade pip

# -------------------------------------------------------------------------------------
# Install NetBox
# -------------------------------------------------------------------------------------
RUN git clone --single-branch --branch ${netbox_ver} https://github.com/netbox-community/netbox.git /opt/netbox/ && \
    cd /opt/netbox/ && \
    pip install -r /opt/netbox/requirements.txt

# -------------------------------------------------------------------------------------
# Install Netbox Plugin
# -------------------------------------------------------------------------------------
RUN mkdir -p /source
WORKDIR /source
COPY . /source

#RUN pip install -r requirements.txt
RUN python setup.py develop

WORKDIR /opt/netbox/netbox/

```

develop/docker-compose.yml (Original):
```
---
version: '3'
services:
  netbox:
    build:
      context: ../
      dockerfile: develop/Dockerfile
    command: >
      sh -c "python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      - postgres
      - redis
    env_file:
      - ./dev.env
    volumes:
      - ./configuration.py:/opt/netbox/netbox/netbox/configuration.py
      - ../netbox_qrcode:/source/netbox_qrcode
    tty: true
  worker:
    build:
      context: ../
      dockerfile: develop/Dockerfile
    command: sh -c "python manage.py rqworker"
    depends_on:
      - netbox
    env_file:
      - ./dev.env
    volumes:
      - ./configuration.py:/opt/netbox/netbox/netbox/configuration.py
      - ../netbox_qrcode:/source/netbox_qrcode
    tty: true
  postgres:
    image: postgres:12
    env_file: dev.env
    volumes:     
      - pgdata_netbox_qrcode:/var/lib/postgresql/data
  redis:
    image: redis:5-alpine
    command:
      - sh
      - -c  # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD  ## $$ because of docker-compose
    env_file: ./dev.env
volumes:
  pgdata_netbox_qrcode:
```

**My "develop/docker-compose-debug.yml"**
```
# Start debugging via Terminal:
# docker-compose -f develop/docker-compose.yml -f develop/docker-compose-debug.yml up --build

---
version: '3'
services:
  netbox:
    build:
      context: ../
      dockerfile: develop/Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python manage.py migrate && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py && runserver 0.0.0.0:8000"]
    ports:
      - '8000:8000'
      - '5678:5678'
    depends_on:
      - postgres
      - redis
    env_file:
      - ./dev.env
    volumes:
      - ./configuration.py:/opt/netbox/netbox/netbox/configuration.py
      - ../netbox_qrcode:/source/netbox_qrcode
    tty: true
```

**MY .vscode/launch.json**
```
{
    "configurations": [
        {
            "name": "Docker: Python - Django",
            "type": "debugpy",
            "request": "attach",
            "connect": {
                "host": "localhost",
                "port": 5678
            },

            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "/source"
                }
            ],
            "django": true,

            "justMyCode": true,

            
        }
    ]
}
```

**MY .vscode/tasks.json**

```
{
    "version": "2.0.0",
    "tasks": [
        { 
            "label": "docker-run: debug",
            "type": "docker-compose",
            "dockerCompose": {
            "up": {
                "detached": true,
                "build": true
            },
            "files": [
                "${workspaceFolder}/develop/docker-compose.yml",
                ]
            }
        }
    ]
  }
```

I then start docker Compose Debug via:
`docker-compose -f develop/docker-compose.yml -f develop/docker-compose-debug.yml up --build`
and then via Run and Debug
