### ISSUE TITLE
Can't connect to host if the docker-compose is created as a pre launch task

### ISSUE THREAD

**Issue by yogaxpto** [microsoft/debugpy#954]
Before creating a new issue, please check the [FAQ](https://github.com/microsoft/debugpy/wiki/FAQ) to see if your question is answered there.

## Environment data

- debugpy version: 1.6.0
- OS and version: Mac OS
- Python version (& distribution if applicable, e.g. Anaconda): XXX
- Using VS Code or Visual Studio: VS Code

## Actual behavior

I've created a simple `Django attach` launch configurations with a `preLaunchTask`which runs the `docker-compose.debug.yml` file before the launch like so:

launch.json
```json
{
    "configurations": [
        {
            "name": "Run Django with compose",
            "type": "python",
            "request": "attach",
            "preLaunchTask": "docker-compose: up",
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}/",
                    "remoteRoot": "/app"
                }
            ],
            "port": 5678,
            "host": "localhost",
        }
    ]
}
```

task.json:
```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "docker-compose",
			"label": "docker-compose: up",
			"dockerCompose": {
				"up": {
					"detached": true,
					"build": true,
				},
				"files": [
					"${workspaceFolder}/docker-compose.debug.yml",
				],
			}
		}
	]
}
```

```yaml
version: '3'

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000"
      ]
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - ./:/app/
```

## Expected  behavior

That vscode would the debugger to the running container without having to deploy the compose mannually.

## Steps to reproduce:
1. Create a Django project;
2. Run `Docker: Add Docker Compose Files to Workspace...`;
3. Create a task to run the docker compose;
4. set the previously created task as a `preLaunchTask` in the defined launch configuration;
5. press `F5`
